set_property SRC_FILE_INFO {cfile:C:/Users/admin/Desktop/ButtonTest/constraint/newconst.xdc rfile:../../../../../../constraint/newconst.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/admin/Desktop/ButtonTest/work/constraint/custom.xdc rfile:../../../../../constraint/custom.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
=set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports {clk}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports {rst_n}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports {usb_rx}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports {usb_tx}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {buttonin[0]}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {buttonout[0]}]
